### ISSUE TITLE
Courses from UTM are not showing up

### ISSUE THREAD

**Issue by SwapnilShahGit** [cobalt-uoft/documentation#34]
This GET request only returns back courses from St.George: https://cobalt.qas.im/api/1.0/courses/search?q="Introduction to Computer Programming"

I have tried searching with the id as well and have not been able to. Any suggestions?

**Comment by SwapnilShahGit** [comment]
https://cobalt.qas.im/api/1.0/courses/filter?q=term:"2016 Fall" AND campus:"UTM" 

is returning "[]"

**Comment by kashav** [comment]
Looks like both UTM and UTSC courses (and I assume some UTSG ones as well) have not made it into the database, [`/api/1.0/courses/filter?q=campus:!"UTSG"`](https://cobalt.qas.im//api/1.0/courses/filter?q=campus:!"UTSG") is also returning `[]`. 

The [dataset](https://raw.githubusercontent.com/cobalt-uoft/datasets/master/courses.json) seems to be fine, I assume there's a problem somewhere along the import pipeline, @qasim should be able to figure out what's going on.

Until then, if you need access to the data, you can use the dataset ([mongoimport](https://docs.mongodb.com/manual/reference/program/mongoimport/) lets you import the line-delimited JSON to MongoDB) or try [self hosting](https://github.com/cobalt-uoft/documentation/blob/master/getting-started/self-hosting.md) the API.

**Comment by qasim** [comment]
Not sure what's going on here. We really need to improve our logging / crash / usage monitoring. I noticed we haven't spent a lot of time there, so it's hard to debug things like this.

I think it's fixed now, but let me know if you encounter it again. Going to leave this issue open until we can confirm it's fixed for good!

**Comment by kashav** [comment]
Looks like this is happening again.

**Comment by qasim** [comment]
Fixed by https://github.com/cobalt-uoft/uoft-scrapers/commit/d69e1cbc782c9031c90548783563d01f044497be
