### ISSUE TITLE
Courses Endpoints: Enrollment is always at zero

### ISSUE THREAD

**Issue by ghost** [cobalt-uoft/documentation#35]
When searching for courses that are full or not (cross referenced from course finder), the enrolment numbers are always zero.

For example, https://cobalt.qas.im/api/1.0/courses/search?q=ENG234H1S, which cross referenced with course finder has like 101/124 people enrolled, but the api still returns 0.

**Comment by kashav** [comment]
@George4564 Thanks for reporting! [Looks like we have a `0` hardcoded for `enrolment` right now](https://github.com/cobalt-uoft/uoft-scrapers/blob/master/uoftscrapers/scrapers/courses/__init__.py#L218). 

https://github.com/cobalt-uoft/uoft-scrapers/pull/83 should fix this.
