### ISSUE TITLE
Cannot filter code and day at the same time

### ISSUE THREAD

**Issue by TimCosby** [cobalt-uoft/documentation#36]
A bit of a weird bug. You are able to filter code and term; day and term, but not code and day or else you get a b'{"error":{"code":500,"message":"TypeError: value is undefined :\\n_funcs1@:31:1\\n"}}'

**Comment by kashav** [comment]
Looks like this is happening when you mix `code` with **any** [nested](https://github.com/cobalt-uoft/cobalt/blob/master/src/api/courses/routes/filter.js#L19:L27) field.

i.e.

- [`/api/1.0/courses/filter?q=start:36000`](https://cobalt.qas.im/api/1.0/courses/filter?q=day:start:36000&key=) responds without error.

- [`/api/1.0/courses/filter?q=day:"Monday" AND start:36000`](https://cobalt.qas.im/api/1.0/courses/filter?q=day:%22Monday%22%20AND%20start:36000&key=) also responds without error.

- [`/api/1.0/courses/filter?q=term:"2016 Fall" AND start:36000`](https://cobalt.qas.im/api/1.0/courses/filter?q=term:%222016%20Fall%22%20AND%20start:36000&key=) also responds without error.

- [`/api/1.0/courses/filter?q=name:"Facing" AND start:36000`](https://cobalt.qas.im/api/1.0/courses/filter?q=name:%22Facing%22%20AND%20start:36000&key=) also responds without error.

- [`/api/1.0/courses/filter?q=code:"CSC" AND start:36000`](https://cobalt.qas.im/api/1.0/courses/filter?q=code:%22CSC%22%20AND%20start:36000&key=) responds with the `TypeError` that @ninjayoshi reported.

Can confirm that this is a bug with the API, added the following tests to our `courses` tests (we weren't testing any `code`/non-nested cases before 😭) and the tests _did_ fail.

```js
test.cb('/filter?q=code:"BIO" AND start:15', t => {
  request(cobalt.Server)
    .get('/1.0/courses/filter?q=code:"BIO" AND start:15')
    .expect('Content-Type', /json/)
    .expect(200)
    .end((err, res) => {
      if (err) t.fail(err.message)
      t.pass()
      t.end()
    })
})

test.cb('/filter?q=code:"BIO" OR day:"THURSDAY"', t => {
  request(cobalt.Server)
    .get('/1.0/courses/filter?q=code:"BIO" OR day:"THURSDAY"')
    .expect('Content-Type', /json/)
    .expect(200)
    .end((err, res) => {
      if (err) t.fail(err.message)
      t.pass()
      t.end()
    })
})
```

Going to look into this, will update if/when I find something.

**Comment by kashav** [comment]
OK, found it - 

[This](https://github.com/cobalt-uoft/cobalt/blob/master/src/api/courses/routes/filterMapReduce.js#L21) should be checking `meeting_code`, not `code` --

```diff
- if (['code', 'size', 'enrolment', 'instructor'].indexOf(p.key) > -1)
+ if (['meeting_code', 'size', 'enrolment', 'instructor'].indexOf(p.key) > -1)
```

**Comment by qasim** [comment]
Oops... nice find @kshvmdn. 😅 Do you want to merge a fix or should we make another issue in the main repo and deal with it from there?

Edit: You beat my comment, awesome 😎

**Comment by qasim** [comment]
Just pushed the patch live. Should be fixed. Try [`/api/1.0/courses/filter?q=code:"CSC" AND start:36000`](https://cobalt.qas.im/api/1.0/courses/filter?q=code:%22CSC%22%20AND%20start:36000&key=) now!
