### ISSUE TITLE
ECE values not showing up

### ISSUE THREAD

**Issue by TimCosby** [cobalt-uoft/documentation#37]
code:ECE as well as department:"Engineering" returns []

**Comment by qasim** [comment]
Thanks for reporting @ninjayoshi. There's been a bug for a while that is preventing courses other than those from `UTSG Arts & Science` from showing up in the hosted API's database. They are in the datasets, however: https://raw.githubusercontent.com/cobalt-uoft/datasets/master/courses.json

I'll try and have a look at this as soon as I can, I think it's got to do with something weird happening in the data pipeline (scraper -> dataset -> database).

Related to #34

**Comment by qasim** [comment]
Fixed by https://github.com/cobalt-uoft/uoft-scrapers/commit/d69e1cbc782c9031c90548783563d01f044497be
